name = "hoyt-kids-chat"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-01-01"

build = { command = "npm run build", cwd = "./" }
main = "dist"

[env.production]
